<img src="https://ga-curriculum.github.io/universal-resources-internal/ga-logos/ga-red-cog-72x72.png" alt="" style="float: left; margin: 20px 20px 0 0; height: 55px">

# Database Lab: Dragon Sword Brigade

_Author: Tim Book_

---

### Objective
You are the new **Analytics Engineer** hired by a game design company to work on the data behind their new title: **Dragon Sword Brigade**, conveniently we can abbreviate this **DSB**.

The previous analytics engineer didn't really know what they were doing, so they just started compiling their data into **One Big Table (OBT)**. This makes it really difficult for other employees to work with the data. As the new engineer, it's your job to clean up this file, create a normalized database, and create some **mart** tables for your data analyst colleagues to work with!

### Step 0: Imports

In [1]:
# Put all imports here.
import numpy as np
import pandas as pd
import sqlite3

### Step 1: Import the table
The **One Big Table (OBT)** data architecture is a legitimate strategy for some organizations. Ours isn't one of them. Import the table using Pandas now and take a look at it.

In [2]:
obt = pd.read_csv('data/dsb-full-data.csv')
obt.head()

,character_name,xp,gold,guild,level,character_id,guild_id,class,user_id,first,last,email,cc_number,cc_expire,cc_security
0,Arinthal,4759,6337,Blades of Valoria,14,3637b0973159e0f9,e9c3b0d506c11b1c,"ranger, bard",27f03e4c3c73b776,William,English,william.english@gmail.com,4332902193345137,01/26,188
1,Darion,1778,52334,Shadowveil Assassins,6,9bb0a13051ff749a,52f6902bcca61a6a,druid,b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
2,Orinthor,4475,60097,Guardians of the Dawn,13,35f0ede436c0dc11,9ef1a491982cbf06,"paladin, cleric",b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
3,Zephira,1955,92548,Dragonheart Syndicate,6,9774f1bd1793c7c6,d96e0324970f052f,"rogue, rogue",b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
4,Kalthar,6117,33505,Stormriders,18,ee0f7ff461e2673c,8f988bdc8e02453c,"necromancer, ranger",f9dd9b9640387403,Crystal,Weaver,crystal.weaver@gmail.com,2532469005140959,08/29,106

### Step 2: Entities

In this game, users create an account with their email. In the game, users can create multiple characters. Characters can only belong to one guild, but a guild may have many members. For in-app purchases, we also store users' payment information. A user may supply us with multiple credit cards.

What entities exist in this table? List them out.

_Hint:_ There are four.

In [3]:
# Solution:
# - Characters
# - Guilds
# - Users
# - Payment options

### Step 3: Create the normalized tables in Pandas

For each of the four entities you listed in the previous step, create a normalized `DataFrame` in Pandas for each of them. Make sure to include foreign keys you think will link out to other tables. In the next step, you'll be asked to create an ERD based on this.

_Hint:_ Fully normalized tables won't have duplicates. You will make heavy use of the `.drop_duplicates()` method in this step.

_Double Hint:_ In cases where certain entities have no match to another entity, this method can produce unexpected NAs. Look for missing values before proceeding to the next step!

In [4]:
users = obt[['user_id', 'first', 'last', 'email']].drop_duplicates()
users.head()

            user_id    first     last                      email
0  27f03e4c3c73b776  William  English  william.english@gmail.com
1  b0c42a8323d7bd33     Dawn    Jones       dawn.jones@gmail.com
4  f9dd9b9640387403  Crystal   Weaver   crystal.weaver@gmail.com
5  d691cbc37599dd32  Anthony  Swanson  anthony.swanson@gmail.com
9  0647e0ef67cec829   Robert    Brown     robert.brown@gmail.com

In [5]:
payment_methods = obt[['user_id', 'cc_number', 'cc_expire', 'cc_security']].drop_duplicates()
payment_methods.head()

            user_id         cc_number cc_expire  cc_security
0  27f03e4c3c73b776  4332902193345137     01/26          188
1  b0c42a8323d7bd33  3505787210639965     04/33          202
4  f9dd9b9640387403  2532469005140959     08/29          106
5  d691cbc37599dd32     4373525223480     06/34          841
6  d691cbc37599dd32  4159876961996315     08/31          279

In [6]:
characters = obt[['character_id', 'character_name', 'xp', 'level', 'gold', 'class', 'guild_id', 'user_id']].drop_duplicates()
characters.head()

,character_id,character_name,xp,level,gold,class,guild_id,user_id
0,3637b0973159e0f9,Arinthal,4759,14,6337,"ranger, bard",e9c3b0d506c11b1c,27f03e4c3c73b776
1,9bb0a13051ff749a,Darion,1778,6,52334,druid,52f6902bcca61a6a,b0c42a8323d7bd33
2,35f0ede436c0dc11,Orinthor,4475,13,60097,"paladin, cleric",9ef1a491982cbf06,b0c42a8323d7bd33
3,9774f1bd1793c7c6,Zephira,1955,6,92548,"rogue, rogue",d96e0324970f052f,b0c42a8323d7bd33
4,ee0f7ff461e2673c,Kalthar,6117,18,33505,"necromancer, ranger",8f988bdc8e02453c,f9dd9b9640387403

In [7]:
guilds = obt[['guild_id', 'guild']].drop_duplicates().dropna()
guilds.head()

           guild_id                  guild
0  e9c3b0d506c11b1c      Blades of Valoria
1  52f6902bcca61a6a   Shadowveil Assassins
2  9ef1a491982cbf06  Guardians of the Dawn
3  d96e0324970f052f  Dragonheart Syndicate
4  8f988bdc8e02453c            Stormriders

### Step 4: ERD

* Create an ERD using [draw.io](draw.io). Draw.io is free and has templates for ERDs in the side bar (look under "Entity Relation" on the left navbar). Make sure to include information such as primary key, foreign key, and use the correct arrows to show relationships.
* Create an `erd` folder in this repo and put a screenshot of your ERD in that. Use Markdown to put the ERID right here in the notebook:

```
PUT ERD RIGHT HERE vvv
```

![](erd/dsb-erd.png)

```
PUT ERD RIGHT HERE ^^^
```

### Step 5: Create the dsb db!

Using SQLite3, create a file called `dsb.db` and insert all 4 `DataFrames`. Note that you don't need to necessarily go through the `CREATE TABLE ()` steps here since Pandas' `.to_sql()` step handles the hard parts for us, although it doesn't enforce things like keys, schemas, nulls, etc.

_Hint:_ Remember to use `index=False` when writing SQL tables!

In [8]:
conn = sqlite3.connect('dsb.db')

In [9]:
users.to_sql('users', conn, if_exists='replace', index=False)
payment_methods.to_sql('payment_methods', conn, if_exists='replace', index=False)
characters.to_sql('characters', conn, if_exists='replace', index=False)
guilds.to_sql('guilds', conn, if_exists='replace', index=False)

### Step 6: Create some requested mart tables

Now that you've got your database ready to go, your Slack notifications are absolutely popping off. The BI (Business Intelligence) Team wants some tables that are ready to go for analysis. This means they already have to be usable so that they can be ported directly into Tableau for immediate visualization. To put it technically, **it's been requested that we make some mart tables!**

#### How You'll be doing this:
* In real life, we'd use a tool such as **dbt** to manage our data warehouse, including mart tables. We won't be setting up dbt as part of this lab.
* In this lab, I want you to use **ONLY SQL!!!!!!** to query your database through Pandas. That is, the only Python code you're writing here is the glue that executes your SQL queries.
* You do not need to save the mart tables anywhere. But for some added practice, you may wish to add them back into the database with the `mart_` prefix. For example, you might name the solution to the first problem below as `mart_guild_roster`.

#### Mart Table 1: Guild Analytics

Create a `guild_roster` table that includes each guild ID, guild name, and how many characters are in each guild.

In [10]:
query = """
SELECT
    g.guild_id,
    g.guild,
    COUNT(c.character_name) AS n_members
FROM guilds AS g
LEFT JOIN characters AS c
ON c.guild_id = g.guild_id
GROUP BY g.guild_id, g.guild
"""

guild_roster = pd.read_sql(query, conn)
guild_roster.head()

           guild_id                   guild  n_members
0  026359fd1703738d        The Gilded Hawks          9
1  16e39a8ea74f6441         Lunar Sentinels         15
2  1827bb8ad3952c28  The Arcane Brotherhood          2
3  21d81b18d525e659           Wraithwalkers          7
4  4103fe5dbe3b8825    Order of the Phoenix          8

#### Mart Table 2: Characters Cleaned

Create a version of the `characters` table denormalized to include:
* The user's full name (one field!)
* The user's email address
* The character's guild

In [11]:
query = """
SELECT
    c.*,
    u.first || " " || u.last AS full_name,
    u.email,
    g.guild_id,
    g.guild
FROM characters AS c
LEFT JOIN users AS u
ON u.user_id = c.user_id
LEFT JOIN guilds AS g
ON g.guild_id = c.guild_id
"""

character_cleaned = pd.read_sql(query, conn)
character_cleaned.head()

,character_id,character_name,xp,level,gold,class,guild_id,user_id,full_name,email,guild_id,guild
0,3637b0973159e0f9,Arinthal,4759,14,6337,"ranger, bard",e9c3b0d506c11b1c,27f03e4c3c73b776,William English,william.english@gmail.com,e9c3b0d506c11b1c,Blades of Valoria
1,9bb0a13051ff749a,Darion,1778,6,52334,druid,52f6902bcca61a6a,b0c42a8323d7bd33,Dawn Jones,dawn.jones@gmail.com,52f6902bcca61a6a,Shadowveil Assassins
2,35f0ede436c0dc11,Orinthor,4475,13,60097,"paladin, cleric",9ef1a491982cbf06,b0c42a8323d7bd33,Dawn Jones,dawn.jones@gmail.com,9ef1a491982cbf06,Guardians of the Dawn
3,9774f1bd1793c7c6,Zephira,1955,6,92548,"rogue, rogue",d96e0324970f052f,b0c42a8323d7bd33,Dawn Jones,dawn.jones@gmail.com,d96e0324970f052f,Dragonheart Syndicate
4,ee0f7ff461e2673c,Kalthar,6117,18,33505,"necromancer, ranger",8f988bdc8e02453c,f9dd9b9640387403,Crystal Weaver,crystal.weaver@gmail.com,8f988bdc8e02453c,Stormriders

#### Mart Table 3: Billing Update

Suppose billing rules are going to change for credit cards expiring in or after 2030. Create a table of all the characters (just name and ID is fine) whose users have a credit card expiring in or after 2030, as the characters will need to be notified when doing in-app purchases in-game.

_Note:_ This one is a little tough! Feel free to use ChatGPT.

In [12]:
query = """
WITH cc_exp AS (
    SELECT
        user_id,
        CAST(SUBSTR(cc_expire, -2) AS INTEGER) AS year
    FROM payment_methods
)
SELECT
    c.character_id,
    c.character_name,
    e.user_id,
    e.year AS cc_expire_year
FROM characters AS c
LEFT JOIN cc_exp AS e
ON e.user_id = c.user_id
WHERE year >= 30
"""

billing_update = pd.read_sql(query, conn)
billing_update.head()

       character_id character_name           user_id  cc_expire_year
0  35f0ede436c0dc11       Orinthor  b0c42a8323d7bd33              33
1  9774f1bd1793c7c6        Zephira  b0c42a8323d7bd33              33
2  9bb0a13051ff749a         Darion  b0c42a8323d7bd33              33
3  b133f533a0f5bad3        Eldoris  d691cbc37599dd32              34
4  e11b88be24209fee        Valeria  d691cbc37599dd32              34

#### Mart Table 4: Guild Data

Suppose the BI analysts want to gather guild data alongside character information. Create a mart table that is the character table plus a new column that is the number of guildmates they have. Note that the number of of guildmates is the total number of characters in a character's guild minus one (since they do not count themselves). Make sure to handle the case where a character is not in a guild at all.

In [13]:
query = """
WITH guild_counts AS (
    SELECT
        g.guild_id,
        COUNT(c.character_id) AS n_members
    FROM characters AS c
    LEFT JOIN guilds AS g
    ON g.guild_id = c.guild_id
    WHERE g.guild_id NOT NULL
    GROUP BY g.guild_id
)
SELECT
    c.*,
    CASE
        WHEN gc.n_members IS NULL THEN 0
        ELSE gc.n_members - 1
    END AS n_guildmates
FROM characters AS c
LEFT JOIN guild_counts AS gc
ON c.guild_id = gc.guild_id
"""

guild_data = pd.read_sql(query, conn)
guild_data

,character_id,character_name,xp,level,gold,class,guild_id,user_id,n_guildmates
0,3637b0973159e0f9,Arinthal,4759,14,6337,"ranger, bard",e9c3b0d506c11b1c,27f03e4c3c73b776,6
1,9bb0a13051ff749a,Darion,1778,6,52334,druid,52f6902bcca61a6a,b0c42a8323d7bd33,9
2,35f0ede436c0dc11,Orinthor,4475,13,60097,"paladin, cleric",9ef1a491982cbf06,b0c42a8323d7bd33,6
3,9774f1bd1793c7c6,Zephira,1955,6,92548,"rogue, rogue",d96e0324970f052f,b0c42a8323d7bd33,4
4,ee0f7ff461e2673c,Kalthar,6117,18,33505,"necromancer, ranger",8f988bdc8e02453c,f9dd9b9640387403,9
...,...,...,...,...,...,...,...,...,...
234,9890aed954607f5d,Zythera,1246,4,95609,"warlock, rogue",21d81b18d525e659,989b2cc3f2d36124,6
235,59937c259ae53568,Vesara,3191,10,81380,necromancer,16e39a8ea74f6441,450788967f757794,14
236,aaef03d1bc4dd0ad,Valira,7975,23,93764,"warlock, rogue",b16b3bc0a1387ee0,6caf8303d1bc3903,6
237,21be280e802d1088,Draelor,273,1,57753,"ranger, cleric",None,e2692c752d7ed016,0
238,d6c993eb383f0046,Selin,8638,25,96917,"bard, mage",4103fe5dbe3b8825,ca5315aa61ec77f0,7